#Script import de packages 

#install.packages("rJava")
#library(rJava)
#install.packages("xlsx")
#library(xlsx)
library(openxlsx)
#install.packages("ggplot2")
library(ggplot2)
#install.packages("plyr")
library(plyr)
#install.packages("dplyr")
library(dplyr)
#install.packages("bit64") #A lancer une fois
#install.packages("data.table")
library(data.table)
 #Chargement du package descr
#install.packages("descr")
library(descr)
#install.packages("vctrs")
library(vctrs)
#install.packages("questionr")
library(questionr)
#install.packages("stargazer")
library(stargazer)
#install.packages("tidyverse")
library(tidyverse)
#install.packages("reshape2")
library(reshape2)
#install.packages("writexl")
library(writexl)
#install.packages("readxl")
library(readxl)
#install.packages("readr")
library(readr)
#install.packages("survey")
library(survey)
#install.packages("finalfit")
library(finalfit)
#install.packages("FactoMineR")
library(FactoMineR)
#install.packages("factoextra")
library(factoextra)
library(cluster)
#install.packages("compare")
library(compare)
#install.packages("janitor")
library(janitor)
#install.packages("survey")
library(survey)
#install.packages("questionr")
library(questionr)
library(tidyr)
#install.packages("hot.deck")
library(hot.deck)
#install.packages("VIM")
library(VIM)
#install.packages("reldist")
library(reldist)
#install.packages("Hmisc")
library(Hmisc)
#install.packages("matrixStats")
library(matrixStats)
library(forcats)
#install.packages("data.table")
library(data.table)
#install.packages("insee")
library(insee)
library(dplyr)
#install.packages("pacman")
pacman::p_load(
  lubridate,  # paquet général pour la manipulation et la conversion des dates 
  parsedate,   # a une fonction pour "deviner" les dates désordonnées
  aweek,      # une autre option pour convertir les dates en semaines, et les semaines en dates
  zoo,        # fonctions supplémentaires de date et d'heure
  tidyverse,  # gestion et visualisation des données  
  rio)
library(seasonal)